[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "d2"
version = "0.0.1"

requires-python = ">=3.10"
dependencies = [
    "numpy<2.0",
    "pandas",
    "tqdm",
    "rdkit",
    "python-dotenv",
    "submitit",
    "click",
    "typer",
    "rich",
    "tooltoad @ git+https://github.com/juius/tool-toad.git",
]
[tool.setuptools]
packages = ["d2"]
