# User preferences - copy to 'config.toml' in your network directory

[qm]
temperature = 298.15  # Kelvin
pressure = 1.0        # atm
solvent = "water"
xtb = "gfn2"       # level of theory
dft = "r2scan-3c"  # level of theory for single point energy calculations

[offsets.water]
deprotonation = -0.4059596304589945
protonation = 0.4059596304589945

[fit_params]
a = 0.43496246
b = -114.66798804

[executables]
xtb = "xtb"
crest = "crest"